### PR TITLE
Updates for 1.7 and several debugs

### PR DESCRIPTION
**Pull request by atabakd**
Thank you so much for the excellent code.
I've made several debugs and modifications, e.g.
* removed `convert` as it decreases resolution, and stamping empty pdfs for empty pages to maintain correct order and avoid [repeating of the last page](https://www.pdflabs.com/docs/pdftk-man-page/#dest-op-multistamp).
* I made the code compatible with `rsync`
* I have also removed converting of epubs, because I am not sure what is the best way to do it. If you convert the epub to pdf to retain the annotations, you kind of lose all the benefits of ebooks.

Feel free to reject it if you have objections to any of these changes.

### CODE REVIEW

**Comment by atabakd** [comment]
Forgot to close `)`

**Comment by lschwetlick** [comment]
Hey, thank you for the PR! I'll check it out as soon as I can :)

**Comment by lschwetlick** [comment]
I'm only just now getting round to looking at this. How did you get the rsync to work on your reMarkable? And wouldn't it deinstall with every update?

**Comment by atabakd** [comment]
sorry, I do not know why I didn't get notifications.
You can see how I did the rsync in my [clone](https://github.com/atabakd/rMsync).
However, the rm2svg is [broken](https://github.com/reHackable/maxio/issues/28) with 1.8 update.
But, via the web interface, I can get the correct annotated PDFs, so I guess we may not need to use the converter part of the code (which is good news).
I now only miss the `backup` and `upload` options.

**Pull request closed without merging**
